name: FTP Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # (Optional) print repo tree once to confirm paths
      - name: Show repo tree
        run: |
          pwd
          ls -la
          find . -maxdepth 2 -type d -print

      - name: FTP Deploy (repo root -> FTP home)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}

          # Because your FTP user lands in /home/officialmobile/nisan.co.in,
          # deploy to that *login root* by setting server-dir to "/"
          server-dir: /               # ✅ no duplication now

          # Upload the repo root (change if your site lives in a subfolder)
          local-dir: ./               # MUST end with a slash

          # Use FTPS if supported, otherwise remove this line
          protocol: ftp

          # Optional: wipe leftovers so old files don't accumulate
          dangerous-clean-slate: true

          exclude: |
            **/.git*
            **/.github/**
            **/.DS_Store
            **/node_modules/**
            **/vendor/**
