name: FTP Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Optional: show repo tree in logs once, helpful for debugging paths
      - name: Show repo tree
        run: |
          pwd
          ls -la
          find . -maxdepth 2 -type d -print

      - name: FTP Deploy (repo root -> /nisan.co.in)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          server-dir: /nisan.co.in/     # your real site folder
          local-dir: ./                 # deploy the repo ROOT (must end with /)
          # protocol: ftps              # uncomment if your host supports FTPS; otherwise plain FTP
          dangerous-clean-slate: true   # removes stray old files on the server
          exclude: |
            **/.git*
            **/.github/**
            **/.DS_Store
            **/node_modules/**
            **/vendor/**
