name: Deploy via FTP on push to main

on:
  push:
    branches: [ "main" ]

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          # pick the correct one and delete the other:
          server-dir: /nisan.co.in/
          # server-dir: /public_html/nisan.co.in/

          local-dir: .
          protocol: ftps           # if your host doesn't support FTPS, delete this line
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/vendor/**
            **/.DS_Store
