name: FTP Deploy

on:
  push:
    branches: [ "main" ]   # deploy on pushes to main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: FTP Deploy (incremental, no wipe)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server:   ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}

          # Your FTP user already lands in /home/officialmobile/nisan.co.in
          # so deploy to the login root to avoid /nisan.co.in/nisan.co.in duplication
          server-dir: /

          # Upload from the repo root (change if your site lives in a subfolder)
          local-dir: ./               # MUST end with /

          # Use FTPS if your host supports it; otherwise remove this line
          protocol: ftp

          # IMPORTANT: no full wipe, fast incremental sync
          # (just omit dangerous-clean-slate entirely)
          exclude: |
            **/.git*
            **/.github/**
            **/.DS_Store
            **/node_modules/**
            **/vendor/**
