name: FTP Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          server-dir: /nisan.co.in/     # ← your real server folder
          local-dir: ./                 # ← deploy the repo root (must end with /)
          protocol: ftp                 # use ftps if supported
          exclude: |
            **/.git*
            **/.github/**
            **/.DS_Store
            **/node_modules/**
            **/vendor/**
          dangerous-clean-slate: true   # optional: removes old stray files on server
