name: Deploy via FTP on push to main

on:
  push:
    branches: [ "main" ]

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: FTP Deploy
  uses: SamKirkland/FTP-Deploy-Action@v4.3.5
  with:
    server: ${{ secrets.FTP_HOST }}
    username: ${{ secrets.FTP_USER }}
    password: ${{ secrets.FTP_PASS }}
    server-dir: /nisan.co.in/          # or /public_html/nisan.co.in/
    local-dir: ./                       # ← add the trailing slash
    protocol: ftps                      # remove if your host doesn’t support FTPS
    exclude: |
      **/.git*
      **/.github/**
      **/node_modules/**
      **/vendor/**
      **/.DS_Store

